/**
 * §B Semantic Icon Registry — single source of truth for icon→concept mapping.
 * Feature code imports from here, never from 'lucide-react' directly.
 */
import {
  Monitor,
  Video,
  Circle,
  WifiOff,
  BarChart3,
  Database,
  HeartPulse,
  Sparkles,
  Map,
  Play,
  Download,
  Search,
  Filter,
  Plus,
  Pencil,
  Trash2,
  Bookmark,
  Move,
  Radio,
  Settings,
  User,
  Users,
  Square,
  Bell,
  FileText,
  Calendar,
  RefreshCw,
  Crosshair,
  X,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Grid2x2,
  List,
  Pin,
} from 'lucide-react'

export const Icon = {
  server:          Monitor,
  camera:          Video,
  recording:       Circle,
  disconnected:    WifiOff,
  analytics:       BarChart3,
  storage:         Database,
  health:          HeartPulse,
  ai:              Sparkles,
  map:             Map,
  playback:        Play,
  export:          Download,
  search:          Search,
  filter:          Filter,
  add:             Plus,
  edit:            Pencil,
  delete:          Trash2,
  bookmark:        Bookmark,
  ptz:             Move,
  live:            Radio,
  settings:        Settings,
  user:            User,
  users:           Users,
  zone:            Square,
  alert:           Bell,
  audit:           FileText,
  calendar:        Calendar,
  sync:            RefreshCw,
  calibrate:       Crosshair,
  close:           X,
  'chevron-up':    ChevronUp,
  'chevron-down':  ChevronDown,
  'chevron-left':  ChevronLeft,
  'chevron-right': ChevronRight,
  grid:            Grid2x2,
  list:            List,
  pin:             Pin,
} as const

export type IconName = keyof typeof Icon
